-- V5: Seed demo employee profiles
-- Description: Creates profiles for the 3 demo users (manager, emp1, emp2)
--              Idempotent: Uses INSERT...ON CONFLICT DO NOTHING

-- Insert profile for Manager (employee_id: MGR001)
INSERT INTO employee_profiles (
    id,
    user_id,
    legal_first_name,
    legal_last_name,
    department,
    job_code,
    job_family,
    job_level,
    employment_status,
    hire_date,
    fte,
    preferred_name,
    job_title,
    office_location,
    work_phone,
    work_location_type,
    bio,
    skills,
    personal_email,
    personal_phone,
    date_of_birth,
    absence_balance_days,
    salary,
    performance_rating
)
SELECT
    gen_random_uuid(),
    u.id,
    'Test',
    'Manager',
    'Engineering',
    'ENG-MGR-001',
    'Engineering',
    'Senior Manager',
    'ACTIVE',
    '2018-01-15',
    1.00,
    'Test Manager',
    'Engineering Manager',
    'Berlin Office',
    '+49-30-12345-100',
    'HYBRID',
    'Experienced engineering manager with 10+ years in software development and team leadership.',
    'Leadership, Team Management, Software Architecture, Agile, Strategic Planning',
    'test.manager@example.de',
    '+49-170-1234567',
    '1985-03-20',
    20.00,
    125000.00,
    'Exceeds Expectations'
FROM users u
WHERE u.employee_id = 'MGR001'
ON CONFLICT (user_id) DO NOTHING;

-- Insert profile for Employee 1 (employee_id: EMP001)
INSERT INTO employee_profiles (
    id,
    user_id,
    legal_first_name,
    legal_last_name,
    department,
    job_code,
    job_family,
    job_level,
    employment_status,
    hire_date,
    fte,
    preferred_name,
    job_title,
    office_location,
    work_phone,
    work_location_type,
    bio,
    skills,
    personal_email,
    personal_phone,
    date_of_birth,
    absence_balance_days,
    salary,
    performance_rating
)
SELECT
    gen_random_uuid(),
    u.id,
    'Test',
    'Employee1',
    'Engineering',
    'ENG-DEV-001',
    'Engineering',
    'Senior Software Engineer',
    'ACTIVE',
    '2020-06-01',
    1.00,
    'Test Employee 1',
    'Senior Software Engineer',
    'Munich Office',
    '+49-89-12345-101',
    'REMOTE',
    'Full-stack developer passionate about building scalable applications and mentoring junior developers.',
    'React, TypeScript, Java, Spring Boot, PostgreSQL, AWS, Docker, Kubernetes',
    'test.employee1@example.de',
    '+49-170-2345678',
    '1990-07-15',
    15.00,
    95000.00,
    'Meets Expectations'
FROM users u
WHERE u.employee_id = 'EMP001'
ON CONFLICT (user_id) DO NOTHING;

-- Insert profile for Employee 2 (employee_id: EMP002)
INSERT INTO employee_profiles (
    id,
    user_id,
    legal_first_name,
    legal_last_name,
    department,
    job_code,
    job_family,
    job_level,
    employment_status,
    hire_date,
    fte,
    preferred_name,
    job_title,
    office_location,
    work_phone,
    work_location_type,
    bio,
    skills,
    personal_email,
    personal_phone,
    date_of_birth,
    absence_balance_days,
    salary,
    performance_rating
)
SELECT
    gen_random_uuid(),
    u.id,
    'Test',
    'Employee2',
    'Engineering',
    'ENG-DEV-002',
    'Engineering',
    'Software Engineer',
    'ACTIVE',
    '2022-03-10',
    1.00,
    'Test Employee 2',
    'Software Engineer',
    'Hamburg Office',
    '+49-40-12345-102',
    'ONSITE',
    'Backend specialist focused on API development and database optimization.',
    'Java, Spring Boot, PostgreSQL, REST APIs, Microservices, Redis',
    'test.employee2@example.de',
    '+49-170-3456789',
    '1992-11-08',
    10.00,
    80000.00,
    'Meets Expectations'
FROM users u
WHERE u.employee_id = 'EMP002'
ON CONFLICT (user_id) DO NOTHING;
